"""empty message

Revision ID: ef3a83cb0178
Revises: 31b21635af8f
Create Date: 2025-06-09 17:20:15.245720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef3a83cb0178'
down_revision = '31b21635af8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.alter_column('diameter_km',
               existing_type=sa.NUMERIC(precision=20, scale=2),
               type_=sa.Float(),
               existing_nullable=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nickname', sa.String(length=16), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('nickname')

    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.alter_column('diameter_km',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=20, scale=2),
               existing_nullable=False)

    # ### end Alembic commands ###
