"""empty message

Revision ID: ff99c9fa8858
Revises: eadbcfc7aae5
Create Date: 2025-06-11 15:16:49.376990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff99c9fa8858'
down_revision = 'eadbcfc7aae5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('img_people',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('img_planets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('img_species',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('height', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('hair_color', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('mass', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('skin_color', sa.String(), nullable=False))
        batch_op.alter_column('gender',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
        batch_op.drop_column('eye_color')
        batch_op.drop_column('height_cm')

    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('gravity', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('diameter', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('orbital_period', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('rotation_period', sa.Integer(), nullable=False))
        batch_op.drop_column('diameter_km')

    with op.batch_alter_table('species', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('average_lifespan', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('designation', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('eye_colors', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('hair_colors', sa.String(), nullable=False))
        batch_op.alter_column('average_height',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.drop_column('skin_colors')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(), nullable=False))
        batch_op.create_unique_constraint(None, ['nickname'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('description')

    with op.batch_alter_table('species', schema=None) as batch_op:
        batch_op.add_column(sa.Column('skin_colors', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
        batch_op.alter_column('average_height',
               existing_type=sa.Integer(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
        batch_op.drop_column('hair_colors')
        batch_op.drop_column('eye_colors')
        batch_op.drop_column('designation')
        batch_op.drop_column('average_lifespan')
        batch_op.drop_column('description')

    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('diameter_km', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
        batch_op.drop_column('rotation_period')
        batch_op.drop_column('orbital_period')
        batch_op.drop_column('diameter')
        batch_op.drop_column('gravity')
        batch_op.drop_column('description')

    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.add_column(sa.Column('height_cm', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('eye_color', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
        batch_op.alter_column('gender',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
        batch_op.drop_column('skin_color')
        batch_op.drop_column('mass')
        batch_op.drop_column('hair_color')
        batch_op.drop_column('height')
        batch_op.drop_column('description')

    op.drop_table('img_species')
    op.drop_table('img_planets')
    op.drop_table('img_people')
    # ### end Alembic commands ###
